[program:automation]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s"
command=/usr/bin/python3 -m uvicorn neko_automation.main:app --host 0.0.0.0 --port 9100 --app-dir /opt/neko-automation --workers 1 --timeout-keep-alive 75
directory=/opt/neko-automation
stopsignal=TERM
stopwaitsecs=20
autorestart=true
priority=900
user=%(ENV_USER)s
stdout_logfile=/var/log/neko/automation.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
redirect_stderr=true
